###

GET http://127.0.0.1:8000/api/booking/reservation-applications
Content-Type: application/json

###
POST http://127.0.0.1:8000/api/booking/reservation-applications/register
Content-Type: application/json

{
  "description": "Reservation",
  "customer": "C02",
  "venue": "V01",
  "from_date": "2022-01-19T00:00:00+08:00",
  "to_date": "2022-01-20T00:00:00+08:00"
}

###
