from enum import Enum


class ReservationApplicationEvents(Enum):
    RESERVATION_APPLICATION_VIEWED = "RESERVATION_APPLICATION_VIEWED"
    RESERVATION_APPLICATION_SAVED = "RESERVATION_APPLICATION_SAVED"
    RESERVATION_APPLICATION_REMOVED = "RESERVATION_APPLICATION_REMOVED"
    RESERVATION_APPLICATION_REGISTERED = "RESERVATION_APPLICATION_REGISTERED"
    RESERVATION_APPLICATION_CHECKED = "RESERVATION_APPLICATION_CHECKED"
    RESERVATION_APPLICATION_APPROVED = "RESERVATION_APPLICATION_APPROVED"
    RESERVATION_APPLICATION_REJECTED = "RESERVATION_APPLICATION_REJECTED"
